### ISSUE TITLE
Padding when using gel-1/2

### ISSUE THREAD

**Issue by lukejpreston** [bbc/gel-grid#21]
Because of the padding on `gel-layout__item` you get overflow
If you are going to split by 50% you can not have padding or margin as well e.g.

``` html
<div className='gel-layout'>
  <div className='gel-layout__item gel-1/2'></div>
  <div className='gel-layout__item gel-1/2'></div>
</div>
```

will produce overflow with the second item being on the second line.

Either I am using the API wrong or you need to fix this as I don't want to have to override this

**Comment by lukejpreston** [comment]
A solution is to use 48% which is something getSkeleton do
https://github.com/dhg/Skeleton/blob/master/css/skeleton.css#L79
The tool I was using before swapping to gel-grid

Also this is going to be an issue if you want to have any other proportion exact

**Comment by shaunbent** [comment]
Skeleton uses fluid width columns as well as fluid width gutters, where as the GEL Grid combines fluid width columns and fixed width gutters which change in size at certain breakpoints.

This is achieved by using `boz-sizing: border-box;`, if you do not already have this set globally in your project there is an optional built in fix for this which you can turn on by passing: `$gel-grid-enable--box-sizing` before you import `@import '../gel-grid/grid';`.

More details here: https://github.com/bbc/gel-grid#box-sizing

**Comment by lukejpreston** [comment]
I created a PR which solve my problem

Basically your dist was not up to date but that should matter anymore after #24 has been merged
