### ISSUE TITLE
Confusion around Grandstand repo connection

### ISSUE THREAD

**Issue by JoshHarrington** [bbc/gel-grid#38]
Hi there,

I've been looking to implement the GEL Grid on a site I'm working on. I started by using the html from the [demo page](https://github.com/bbc/gel-grid/blob/master/demo/src/index.html) in this repo, with the thinking that if everything in the demo worked then I it would contain most / all of the functional classes that I would need to use.

However, I came across the `gs-u-mt0@l` class in the demo but couldn't find the relevant scss in this repo or in the [GEL Sass Tools](https://github.com/bbc/gel-sass-tools) repo. Only when I googled round did I find the relevant scss in the [Grandstand repo](https://github.com/bbc/grandstand/blob/master/lib/utilities/_spacing.scss) - which hadn't been mentioned in the README of this repo.

Am I right in thinking that I'd need to include the whole Grandstand repo to ensure that these classes are available? Also are there likely to be other repos that have classes / functions employed in the demo that should be included in my project too?

Also I just wanted to say thanks for putting this out in the wild, really useful having this sort of resource available.

Cheers,
Josh

**Comment by mintuz** [comment]
Hello @JoshHarrington thanks for reaching out. You are correct in saying the demo is confusing and we should probably update it to remove the dependency on Grandstand. 

As for the grid, there is not a direct dependency to use Grandstand to make it work so by default the gs-* classes do not exist. If you wish to use Grandstand, it has a dependency on the grid.

Grandstand has been brought into the demo because the grid does not have vertical rhythm by default.

**Comment by JoshHarrington** [comment]
Hi @mintuz, thanks for getting back to me so quickly.
Ok cheers, that's roughly what I was guessing.

Do you know if there's a plan to incorporate the vertical rhythm logic from Grandstand into this repo in future?

Thanks,
Josh

**Comment by mintuz** [comment]
@JoshHarrington I don't think a plan is in place at the moment but it may be something we do in the future if teams decide it would be a good idea. We tried to keep the gel-grid as light as possible.

**Comment by JoshHarrington** [comment]
@mintuz ok good to know.
Thanks!
