### ISSUE TITLE
Dart Sass Error -  Using / for division is deprecated

### ISSUE THREAD

**Issue by nicholasgriffintn** [bbc/gel-grid#48]
Full error that is shown in the terminal when starting an app that uses dart sass and gel-grid:

https://github.com/bbc/gel-grid/blob/1d48de58ea4c4040530a8a79f8262b0f20bd0fe2/lib/_tools.scss

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($i, $column)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
454 │                 $width: round(($i / $column) * 10000000) / 10000000;
    │                                ^^^^^^^^^^^^
    ╵
    node_modules/gel-grid/lib/_tools.scss 454:32  -gel-widths()
    node_modules/gel-grid/lib/_tools.scss 375:9   gel-output-widths()
    node_modules/gel-grid/_grid.scss 26:5         @import
    src/styles/app.scss 8:9                       root stylesheet
```

**Comment by randombitsUK** [comment]
Thanks for mentioning this @nicholasgriffintn, we are aware of it and have it on our todo list. :)

**Comment by nicholasgriffintn** [comment]
Fantastic, thanks for updated me.

**Comment by randombitsUK** [comment]
@nicholasgriffintn The GEL packages have now been updated and published to address this.

**Note:** A dependency `sass-mq` has now yet addressed this issue, so you will still get some deprecation warning. v6 of `sass-mq` should resolve this, and we'll update to that when it's released.

**Comment by nicholasgriffintn** [comment]
Awesome, I've updated our service and the error has gone away for gel-grid, it's just sass-mq left now yeah.

**Comment by randombitsUK** [comment]
As this has been addressed the issue is being closed.
