### ISSUE TITLE
Readme says there is a compiled version of the SASS in the repo

### ISSUE THREAD

**Issue by DanCorderSoftwire** [bbc/gel-grid#50]
The Readme file says that:

"_The easiest way to get started with the GEL Grid component is to use the compiled version of the grid included within this repository._"

But I can't see a compiled version anywhere. It looks like the only CSS file in the repo currently is a test file: https://github.com/bbc/gel-grid/search?l=css

If a pre-compiled version no longer makes sense (maybe due to the number of options in the SASS) then it would be good to update the readme.

**Comment by DanCorderSoftwire** [comment]
There is https://github.com/bbc/gel-grid.css, but that hasn't been updated since 2016 so I'm assuming that this repo is the current up to date one.

**Comment by randombitsUK** [comment]
The compiled css has been added back in.
