### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by shaunbent** [bbc/gel-grid#7]
News/World Service need the ability to support RTL text and layouts.

We can use `gel-layout--rev` to reverse the layouts of the grid but this includes a forced `text-align`.

We need to introduce a new modifier class of `gel-layout--rtl` which applies: `direction: rtl;` and applies `text-align: start;` to the `gel-layout__item`s.

Here is a codepen of this in action: http://codepen.io/shaunbent/pen/MyqKBQ

**Comment by howieweiner** [comment]
Is there a reason you wouldn't apply the style if the 'dir' attribute has been set, rather than creating a modifier? Applying the style when [dir="rtl"] is present will be applied implicitly. The modifier would need to be applied explicitly by each product.

**Comment by shaunbent** [comment]
Nice @howieweiner, maybe lets do that instead.

**Comment by greenc05** [comment]
Thumbs Up from me @howieweiner @shaunbent
